### ISSUE TITLE
vendor migration with cisco-asa stack-trace

### ISSUE THREAD

**Issue by edergernot** [swaschkut/pan-os-php#27]
vendor migration with cisco-asa errors when in acl is a tcp pornumber.
here a sample config-line:
`access-list CSM_FW_ACL_ advanced trust tcp ifc DMZ-PROJEKTE object-group FMC_INLINE_src_rule_268437650 ifc INSIDE object-group FMC_INLINE_dst_rule_268437650 eq 744 rule-id 268437650 event-log both `

Here a working one.

`access-list CSM_FW_ACL_ advanced trust tcp ifc DMZ-PROJEKTE object-group FMC_INLINE_src_rule_268437650 ifc INSIDE object-group FMC_INLINE_dst_rule_268437650 eq sunrpc rule-id 268437650 event-log both 
access-list CSM_FW_ACL_ advanced trust tcp ifc DMZ-PROJEKTE object-group FMC_INLINE_src_rule_268437650 ifc INSIDE object-group FMC_INLINE_dst_rule_268437650 eq https rule-id 268437650 event-log both 
access-list CSM_FW_ACL_ advanced trust tcp ifc DMZ-PROJEKTE object-group FMC_INLINE_src_rule_268437650 ifc INSIDE object-group FMC_INLINE_dst_rule_268437650 eq rsh rule-id 268437650 event-log both`
Stack Trace:
`
* create securityRule: CSM_FW_ACL__3
    * add Tag: CSM_FW_ACL_
    * set action allow
    * FROM set to DMZ-PROJEKTE
    * add source - addressgroup object: FMC_INLINE_src_rule_268437650
    * TO set to INSIDE
    * add destination - addressgroup object: FMC_INLINE_dst_rule_268437650
    * add service - service object: tcp-514

* create securityRule: CSM_FW_ACL__4
    * add Tag: CSM_FW_ACL_
    * set action allow
    * FROM set to DMZ-PROJEKTE
    * add source - addressgroup object: FMC_INLINE_src_rule_268437650
    * TO set to INSIDE
    * add destination - addressgroup object: FMC_INLINE_dst_rule_268437650
PHP Fatal error:  Uncaught Error: Call to a member function isGroup() on null in /tools/pan-os-php/migration/parser/CISCO/CISCOsecurityrules.php:1029
Stack trace:
#0 /tools/pan-os-php/migration/parser/CISCO/CISCOASA.php(430): CISCOASA->get_security_policies2()
#1 /tools/pan-os-php/migration/parser/CISCO/CISCOASA.php(104): CISCOASA->import_config()
#2 /tools/pan-os-php/migration/parser/lib/CONVERTER.php(763): CISCOASA->vendor_main()
#3 /tools/pan-os-php/migration/parser/lib/CONVERTER.php(90): CONVERTER->main()
#4 /tools/pan-os-php/utils/lib/UTIL.php(215): CONVERTER->utilStart()
#5 /tools/pan-os-php/lib/misc-classes/PH.php(1201): UTIL->__construct()
#6 /tools/pan-os-php/utils/pan-os-php.php(118): PH::callPANOSPHP()
#7 Command line code(1): require_once('...')
#8 {main}
  thrown in /tools/pan-os-php/migration/parser/CISCO/CISCOsecurityrules.php on line 1029
  `

**Comment by swaschkut** [comment]
fix implemented with version 2.1.27
#28
